### PR TITLE
Tests for config parsers

### LINKED ISSUE #371: Add Unit/PhpSpec tests for Taxonomies
See #362

### LINKED ISSUE #379: Improve tests for 'config parsers'
Taken from conversations in different places: 

> How does it break? throws an exception? can you test it? https://github.com/bolt/four/pull/376#discussion_r271286468

> add file name / path as constructor parameter https://github.com/bolt/four/pull/376#discussion_r271527155

It'll require some changes in all 5 files `src/Configuration/Parser`, so it needs to be a separate PR. #376 is getting too big.

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #371. Fixes #379.

### CODE REVIEW

File: src/Configuration/Parser/BaseParser.php [hunk 1]
```diff
@@ -54,5 +69,14 @@ public function getFilenames(): array
         return $this->filenames;
     }
 
+    public function getFilename()
+    {
+        return $this->filename;
+    }
+
+    public function getFilenameLocalOverrides() {
+        return preg_replace('/([a-z0-9_-]+).(ya?ml)$/i', '$1_local.$2', $this->filename);
```
Comment (JarJak) [inline src/Configuration/Parser/BaseParser.php]: why you don't do this Symfony way? https://symfony.com/doc/current/configuration/configuration_organization.html

File: tests/php/Configuration/Parser/MenuParserTest.php [hunk 2]
```diff
@@ -15,10 +17,38 @@ public function testCanParse(): void
...
+        $file = dirname(dirname(dirname(__DIR__))).'/fixtures/config/bogus.yaml';
+        $menuParser = new MenuParser($file);
+        $config = $menuParser->parse();
+
+        $this->assertInstanceOf(Collection::class, $config);
+    }
+
+    public function testBreakOnInvalidFileParse(): void
+    {
+        $file = dirname(dirname(dirname(__DIR__))).'/fixtures/config/broken.yaml';
```
Comment (JarJak) [inline tests/php/Configuration/Parser/MenuParserTest.php]: set const base path

File: tests/php/Configuration/Parser/TaxonomyParserTest.php [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+{
+    public function testCanParse(): void
+    {
+        $taxonomyParser = new TaxonomyParser();
+        $config = $taxonomyParser->parse();
+
+        $this->assertInstanceOf(Collection::class, $config);
+    }
+
+    public function testBreakOnInvalidFileParse(): void
```
Comment (JarJak) [inline tests/php/Configuration/Parser/TaxonomyParserTest.php]: duplicated test

File: src/Configuration/Parser/BaseParser.php (hunk 1 above)
Comment (bobdenotter) [reply src/Configuration/Parser/BaseParser.php]: Like the previous time you asked me this: I don't like that component.. It's too cumbersome for my tastes. ;-)

Comment (JarJak) [reply src/Configuration/Parser/BaseParser.php]: But people are used to use it in Symfony projects. I'd use what community loves.

File: tests/php/Configuration/Parser/TaxonomyParserTest.php (hunk 3 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/TaxonomyParserTest.php]: Except it tests it on a _different_ class.. Really think i should remove it?

File: tests/php/Configuration/Parser/MenuParserTest.php (hunk 2 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/MenuParserTest.php]: Done

**Comment by bobdenotter** [comment]
There's undoubtedly more that can be done, but this feels like a nice wrapped up unit-of-improvement.

File: src/Configuration/Parser/BaseParser.php (hunk 1 above)
Comment (bobdenotter) [reply src/Configuration/Parser/BaseParser.php]: Nah, I'd really like to keep this as is. :-)

Comment (JarJak) [reply src/Configuration/Parser/BaseParser.php]: How can I have more than "normal" and "local" environments then?

Comment (bobdenotter) [reply src/Configuration/Parser/BaseParser.php]: That can be a feature-request for later. ;-)

File: tests/php/Configuration/Parser/TaxonomyParserTest.php [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+    {
+        $file = dirname(dirname(dirname(__DIR__))).'/fixtures/config/broken.yaml';
```
[the remark this answers is not in the document]
Comment (bobdenotter) [reply tests/php/Configuration/Parser/TaxonomyParserTest.php]: Will do that right now.

[the remark this answers is not in the document]
Comment (bobdenotter) [reply tests/php/Configuration/Parser/TaxonomyParserTest.php]: abstract ParserTestBase added

File: src/Configuration/Parser/BaseParser.php (hunk 1 above)
Comment (JarJak) [reply src/Configuration/Parser/BaseParser.php]: Later it can be hard to refactor

File: tests/fixtures/config/minimal_contenttypes.yaml [hunk 5]
```diff
@@ -0,0 +1,11 @@
+# Minimal Contenttypes
+
+foo:
+  name: Bars
```
Comment (JarJak) [inline tests/fixtures/config/minimal_contenttypes.yaml]: name is not needed for minimal Content Type ;)

File: tests/fixtures/config/minimal_contenttypes.yaml [hunk 6]
```diff
@@ -0,0 +1,11 @@
+# Minimal Contenttypes
```
Comment (JarJak) [inline tests/fixtures/config/minimal_contenttypes.yaml]: Content Types*
also change file name

File: tests/php/Configuration/Parser/ContentTypesParserTest.php [hunk 7]
```diff
@@ -69,7 +69,7 @@ public function testHasConfig(): void
         $this->assertCount(6, $config);
 
         $this->assertArrayHasKey('homepage', $config);
-        $this->assertCount(21, $config['homepage']);
+        $this->assertCount(20, $config['homepage']);
```
Comment (JarJak) [inline tests/php/Configuration/Parser/ContentTypesParserTest.php]: What does this magic number mean? Why it has to be 20?

File: tests/php/Configuration/Parser/ContentTypesParserTest.php [hunk 8]
```diff
@@ -81,9 +81,55 @@ public function testHasConfig(): void
...
+        $file = self::getBasePath() . 'minimal_contenttypes.yaml';
+
+        $generalParser = new GeneralParser();
+        $contentTypesParser = new ContentTypesParser($generalParser->parse(), $file);
+        $config = $contentTypesParser->parse();
+
+        $this->assertCount(2, $config);
+
+        $this->assertArrayHasKey('foo', $config);
+        $this->assertCount(20, $config['foo']);
```
Comment (JarJak) [inline tests/php/Configuration/Parser/ContentTypesParserTest.php]: another magic number

File: tests/php/Configuration/Parser/ContentTypesParserTest.php [hunk 9]
```diff
@@ -81,9 +81,55 @@ public function testHasConfig(): void
...
+
+    public function testInferContentTypeValues(): void
+    {
+        $file = self::getBasePath() . 'minimal_contenttypes.yaml';
+
+        $generalParser = new GeneralParser();
+        $contentTypesParser = new ContentTypesParser($generalParser->parse(), $file);
+        $config = $contentTypesParser->parse();
+
+        $this->assertCount(2, $config);
```
Comment (JarJak) [inline tests/php/Configuration/Parser/ContentTypesParserTest.php]: magic number

File: tests/php/Configuration/Parser/ContentTypesParserTest.php [hunk 10]
```diff
@@ -81,9 +81,55 @@ public function testHasConfig(): void
...
+        $this->assertSame(10, $config['foo']['records_per_page']);
+
+        $this->assertIsIterable($config['foo']['fields']);
+        $this->assertIsIterable($config['foo']['locales']);
+        $this->assertIsIterable($config['foo']['groups']);
+        $this->assertIsIterable($config['foo']['taxonomy']);
+        $this->assertIsIterable($config['foo']['relations']);
+
+        $this->assertArrayHasKey('qux', $config);
+        $this->assertCount(20, $config['qux']);
```
Comment (JarJak) [inline tests/php/Configuration/Parser/ContentTypesParserTest.php]: maagic

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 7 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: Because it happens to have 20 items.

File: tests/fixtures/config/minimal_contenttypes.yaml (hunk 6 above)
Comment (bobdenotter) [reply tests/fixtures/config/minimal_contenttypes.yaml]: why change the filename?

File: src/Configuration/Parser/BaseParser.php (hunk 1 above)
Comment (bobdenotter) [reply src/Configuration/Parser/BaseParser.php]: Doing too much now will add needless complexity.

File: tests/fixtures/config/minimal_contenttypes.yaml (hunk 5 above)
Comment (bobdenotter) [reply tests/fixtures/config/minimal_contenttypes.yaml]: Yes it is. Either the name of the slug is required.

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 7 above)
Comment (JarJak) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: But must it be 20 items? In other words, this value is special enough to test it?

Comment (bobdenotter) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: Currently, yes. It should be exactly 20, because that is the number of attributes a ContentType has. If any are missing from the config yaml, they will be set to the default.

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 9 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: There _are_ two in the `minimal_contenttypes.yaml`. What else would I put there?

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 10 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: See above

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 7 above)
Comment (JarJak) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: So can you set it as const in ContentType class?

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 9 above)
Comment (JarJak) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: add `NUMBER_OF_CONTENT_TYPES_IN_MINIMAL_FILE` (or something like this) const to this test class :)

File: tests/fixtures/config/minimal_contenttypes.yaml (hunk 6 above)
Comment (JarJak) [reply tests/fixtures/config/minimal_contenttypes.yaml]: because it uses snake case, so it can be `minimal_content_types.yaml`

File: tests/fixtures/config/minimal_contenttypes.yaml (hunk 5 above)
Comment (JarJak) [reply tests/fixtures/config/minimal_contenttypes.yaml]: but there is a slug in line 3

Comment (bobdenotter) [reply tests/fixtures/config/minimal_contenttypes.yaml]: Added another test for it.

File: tests/fixtures/config/minimal_contenttypes.yaml (hunk 6 above)
Comment (bobdenotter) [reply tests/fixtures/config/minimal_contenttypes.yaml]: We've always used `contenttypes.yml` in `config/` though.. I've changed it, but i'm not sure I like the inconsistency. 🤔

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 9 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: Done.

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 10 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: Done

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 8 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: Changed

File: tests/fixtures/config/minimal_contenttypes.yaml (hunk 6 above)
Comment (JarJak) [reply tests/fixtures/config/minimal_contenttypes.yaml]: This is a "bc break" between 3 and 4 ;) Acually I prefer to call it `Content Definitions` but types is shorter ;)

File: tests/php/Configuration/Parser/ContentTypesParserTest.php [hunk 11]
```diff
@@ -0,0 +1,141 @@
...
+use Bolt\Exception\ConfigurationException;
+use Symfony\Component\Config\Exception\FileLocatorFileNotFoundException;
+use Symfony\Component\Yaml\Exception\ParseException;
+use Tightenco\Collect\Support\Collection;
+
+class ContentTypesParserTest extends ParserTestBase
+{
+    const NUMBER_OF_CONTENT_TYPES_IN_MINIMAL_FILE = 3;
+
+    const AMOUNT_OF_ATTRIBUTES_IN_CONTENTTYPE = 20;
```
Comment (JarJak) [inline tests/php/Configuration/Parser/ContentTypesParserTest.php]: CONTENT_TYPE*

File: tests/fixtures/config/minimal_content_types.yaml [hunk 12]
```diff
@@ -0,0 +1,16 @@
...
+  fields: []
+
+qux:
+  slug: corges
+  singular_slug: corge
+  fields: []
+
+# Infer fields, and determine both the `slug` and `name` get inferred from the key
+grault:
+  singular_name: Waldo
```
Comment (JarJak) [inline tests/fixtures/config/minimal_content_types.yaml]: does it need to have at least one of `singular_name` and `singular_slug`?

File: tests/fixtures/config/minimal_content_types.yaml [hunk 13]
```diff
@@ -0,0 +1,16 @@
...
+  fields: []
```
Comment (JarJak) [inline tests/fixtures/config/minimal_content_types.yaml]: can this line be omitted and fields set as an empty array by default in the parser?

File: src/Configuration/Parser/BaseParser.php [hunk 14]
```diff
@@ -21,22 +21,37 @@ abstract class BaseParser
...
 
     /**
      * Read and parse a YAML configuration file.
+     *
+     * If filename doesn't exist and/or isn't readable, we attempt to locate it
+     * in our config folder. This way you can pass in either  an absolute
+     * filename or simply 'menu.yaml'.
      */
-    protected function parseConfigYaml(string $filename): Collection
+    protected function parseConfigYaml(string $filename, $ignoreMissing = false): Collection
```
Comment (JarJak) [inline src/Configuration/Parser/BaseParser.php]: bool

File: src/Configuration/Parser/BaseParser.php [hunk 15]
```diff
@@ -21,22 +21,37 @@ abstract class BaseParser
     /** @var string[] */
     protected $filenames = [];
 
-    public function __construct()
+    /** @var string */
+    protected $filename;
```
Comment (JarJak) [inline src/Configuration/Parser/BaseParser.php]: what is a difference here between $filename and $filenames?

File: tests/fixtures/config/minimal_content_types.yaml (hunk 12 above)
Comment (bobdenotter) [reply tests/fixtures/config/minimal_content_types.yaml]: Yes. :-)

File: tests/php/Configuration/Parser/ContentTypesParserTest.php (hunk 11 above)
Comment (bobdenotter) [reply tests/php/Configuration/Parser/ContentTypesParserTest.php]: Fixed

File: tests/fixtures/config/minimal_content_types.yaml (hunk 13 above)
Comment (bobdenotter) [reply tests/fixtures/config/minimal_content_types.yaml]: Not really.. If you do, you get an exception by design, to warn the user a contenttype needs fields: 

```
In content type <code>foo</code>, no 'fields' are set. Please edit <code>contenttypes.yml</code>, and correct this.
```

Comment (bobdenotter) [reply tests/fixtures/config/minimal_content_types.yaml]: .. and before you ask.. Yes, this is tested in `testIgnoreNonsensicalFileParse()` ;-)

File: src/Configuration/Parser/BaseParser.php (hunk 14 above)
Comment (bobdenotter) [reply src/Configuration/Parser/BaseParser.php]: done

File: src/Configuration/Parser/BaseParser.php (hunk 15 above)
Comment (bobdenotter) [reply src/Configuration/Parser/BaseParser.php]: Done, see latest commit.

File: tests/fixtures/config/minimal_content_types.yaml (hunk 12 above)
Comment (JarJak) [reply tests/fixtures/config/minimal_content_types.yaml]: why?
